version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:15.0-alpine 
    restart: always
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  backend:
    container_name: backend
    restart: "no"
    build:
      context: .
      dockerfile: cmd/backend/Dockerfile
      target: prod
    environment:
      PORT: 1100
      LOGS_FORMAT: console
      PGHOST: postgres
      PGNAME: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - 1100:1100
    expose:
      - 1100

  migrations:
    container_name: migrations
    image: migrate/migrate:v4.15.2
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:5432/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}&sslmode=disable",
        "-verbose",
        "up",
      ]
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  backups:
    container_name: backups
    image: prodrigestivill/postgres-backup-local:15
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - ./dbbackups:/backups
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EXTRA_OPTS: -Z6 --schema=public --blobs
      SCHEDULE: "@hourly" # valid values are @yearly, @monthly, @weekly, @daily, @hourly
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080

volumes:
  postgres_volume:
