version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: user-development
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: hmm-development
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend:
    container_name: backend
    restart: "no"
    build:
      context: .
      dockerfile: cmd/backend/Dockerfile
      target: prod
    environment:
      STRUCTURED_LOGGING: "false"
    depends_on:
      - database
    links:
      - database
    ports:
      - 1100:1100
    expose:
      - 1100

volumes:
  postgres_volume:
