version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: user-development
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: hmm-development
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  hmm:
    container_name: hmm
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        project: hmm
        project_path: ./cmd/services
    ports:
      - 1100:1100
    command: ./hmm
    environment:
      STRUCTURED_LOGGING: "false"
    depends_on:
      - database
    links:
      - database

volumes:
  postgres_volume:
