version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:15.0-alpine 
    restart: always
    user: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  backend:
    container_name: backend
    restart: "no"
    build:
      context: .
      dockerfile: cmd/backend/Dockerfile
      target: prod
    environment:
      PORT: 1100
      LOGS_FORMAT: console
      STRUCTURED_LOGGING: "false"
      PGHOST: postgres
      PGNAME: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - 1100:1100
    expose:
      - 1100

volumes:
  postgres_volume:
